# Generated by Django 5.2.4 on 2025-08-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024)),
                ('account', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=1024)),
                ('role', models.IntegerField(choices=[(1, 'normal'), (2, 'vip'), (3, 'admin')], default=1, max_length=1024)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
