# Generated by Django 5.2.4 on 2025-08-15 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=1024, unique=True, verbose_name='帳號'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='啟用中'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login_at',
            field=models.DateTimeField(auto_now=True, verbose_name='上次登入時間'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=1024, verbose_name='密碼（雜湊）'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(1, '一般'), (2, 'VIP'), (3, '管理員')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=1024, verbose_name='使用者名稱'),
        ),
    ]
