# Generated by Django 5.2.4 on 2025-08-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1024)),
                ('options_id', models.IntegerField(unique=True)),
                ('sort_order', models.IntegerField()),
                ('answer', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=128)),
                ('Activity_start_date', models.DateTimeField()),
                ('Activity_end_date', models.DateTimeField()),
                ('descripe', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Active_question_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=64)),
                ('option_value', models.CharField(max_length=1024)),
                ('sort_order', models.IntegerField()),
                ('options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_by_options_id', to='events.active_questions')),
            ],
        ),
        migrations.AddField(
            model_name='active_questions',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.activity_form'),
        ),
    ]
