# Generated by Django 5.2.4 on 2025-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_question_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.IntegerField()),
                ('option_label', models.CharField(max_length=64)),
                ('option_value', models.CharField(max_length=1024)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Active_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_id', models.IntegerField()),
                ('question_text', models.CharField(max_length=1024)),
                ('options_id', models.IntegerField()),
                ('sort_order', models.IntegerField()),
                ('answer', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=128)),
                ('Activity_start_date', models.DateTimeField()),
                ('Activity_end_date', models.DateTimeField()),
                ('descripe', models.CharField(max_length=1024)),
            ],
        ),
    ]
