# Generated by Django 5.2.4 on 2025-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_form',
            name='address',
            field=models.CharField(default='as', max_length=1024),
            preserve_default=False,
        ),
    ]
