# Generated by Django 5.2.4 on 2025-08-13 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_activity_form_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=80)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='events.activity_form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(default='', max_length=128)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.activity_form')),
                ('checkpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='events.geocheckpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_in_stage', models.IntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_map', to='events.active_questions')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_maps', to='events.stage')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_stage', models.PositiveSmallIntegerField(default=0)),
                ('last_checkin_at', models.DateTimeField(auto_now=True)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='events.activity_form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='geocheckpoint',
            index=models.Index(fields=['activity', 'order'], name='events_geoc_activit_6eb8af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geocheckpoint',
            unique_together={('activity', 'order')},
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['activity', 'order'], name='events_stag_activit_c9f09b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('activity', 'order')},
        ),
        migrations.AddIndex(
            model_name='questionstage',
            index=models.Index(fields=['stage', 'sort_in_stage'], name='events_ques_stage_i_f4fa3c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'activity'], name='events_user_user_id_b13c33_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['activity', 'unlocked_stage'], name='events_user_activit_3de12e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'activity')},
        ),
    ]
