# Generated by Django 5.2.4 on 2025-08-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_geocheckpoint_stage_questionstage_userprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='questionstage',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionstage',
            name='stage',
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stage',
            name='activity',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeoCheckpoint',
        ),
        migrations.DeleteModel(
            name='QuestionStage',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
