# Generated by Django 5.2.4 on 2025-08-13 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_email'),
        ('events', '0004_remove_stage_checkpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=80)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='events.activity_form')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['activity', 'order'], name='events_geoc_activit_6eb8af_idx')],
                'unique_together': {('activity', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_stage', models.PositiveSmallIntegerField(default=0)),
                ('last_checkin_at', models.DateTimeField(auto_now=True)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='events.activity_form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='accounts.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'activity'], name='events_user_user_id_b13c33_idx'), models.Index(fields=['activity', 'unlocked_stage'], name='events_user_activit_3de12e_idx')],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
