# Generated by Django 5.2.4 on 2025-08-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_geocheckpoint_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_form',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity_form',
            name='lottery_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity_form',
            name='lottery_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity_form',
            name='lottery_quota',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
