# Generated by Django 5.2.4 on 2025-08-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_geocheckpoint_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='lottery_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
