# Generated by Django 5.2.4 on 2025-08-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('address', models.CharField(max_length=255)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('place_id', models.CharField(blank=True, max_length=128)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('event_occurs_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('level', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_records', to='accounts.users')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='records_eve_user_id_7b661c_idx'), models.Index(fields=['place_id'], name='records_eve_place_i_1adf06_idx'), models.Index(fields=['lat', 'lng'], name='records_eve_lat_439e1d_idx'), models.Index(fields=['is_active', 'level'], name='records_eve_is_acti_154a04_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('lat__isnull', True), ('lng__isnull', True)), models.Q(('lat__isnull', False), ('lng__isnull', False)), _connector='OR'), name='lat_lng_both_null_or_both_set')],
            },
        ),
    ]
