# Generated by Django 5.2.4 on 2025-08-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_record',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='records/images/'),
        ),
    ]
