# Generated by Django 5.2.4 on 2025-08-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_event_record_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_record',
            name='descriptions',
            field=models.CharField(default='s', max_length=1028),
            preserve_default=False,
        ),
    ]
