# Generated by Django 5.2.4 on 2025-08-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_users_options_alter_users_account_and_more'),
        ('records', '0004_alter_event_record_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_record',
            options={'ordering': ['-created_at'], 'verbose_name': '上報事件', 'verbose_name_plural': '上報事件'},
        ),
        migrations.AddField(
            model_name='event_record',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='刪除時間'),
        ),
        migrations.AddField(
            model_name='event_record',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已軟刪除'),
        ),
        migrations.AddField(
            model_name='event_record',
            name='review_status',
            field=models.IntegerField(choices=[(1, '待審核'), (2, '已通過'), (3, '已退回')], default=1, verbose_name='審核狀態'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='address',
            field=models.CharField(max_length=255, verbose_name='使用者輸入地址'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='descriptions',
            field=models.CharField(max_length=1028, verbose_name='事件描述'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='事件圖片'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='event_name',
            field=models.CharField(max_length=128, verbose_name='事件名稱'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='event_occurs_time',
            field=models.DateTimeField(verbose_name='事件發生時間'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='正規化地址'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='地理編碼時間'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='顯示在地圖'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='level',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1, verbose_name='等級'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='place_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Place ID'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='event_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_records', to='accounts.users', verbose_name='上報者'),
        ),
        migrations.AddIndex(
            model_name='event_record',
            index=models.Index(fields=['review_status', 'is_deleted'], name='records_eve_review__35575a_idx'),
        ),
    ]
