# Generated by Django 5.2.4 on 2025-08-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_users_email'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_entries', to='events.activity_form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_entries', to='accounts.users')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'is_winning'], name='lottery_lot_activit_227bd1_idx'), models.Index(fields=['user', 'activity', 'created_at'], name='lottery_lot_user_id_74c322_idx')],
            },
        ),
    ]
