# Generated by Django 5.2.4 on 2025-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryentry',
            name='prize',
            field=models.CharField(default='幽約抱枕', max_length=128),
            preserve_default=False,
        ),
    ]
