# Generated by Django 5.2.4 on 2025-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_lotteryentry_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryentry',
            name='times',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
