# Generated by Django 5.2.4 on 2025-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_lotteryentry_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryentry',
            name='is_joined',
            field=models.BooleanField(default=True),
        ),
    ]
